ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-{{ env }}.learndaws.online
CATALOGUE_HOST: catalogue-{{ env }}.learndaws.online
REDIS_HOST: redis-{{ env }}.learndaws.online
USER_HOST: user-{{ env }}.learndaws.online
CART_HOST: cart-{{ env }}.learndaws.online
MYSQL_HOST: mysql-{{ env }}.learndaws.online
SHIPPING_HOST: shipping-{{ env }}.learndaws.online
RABBITMQ_HOST: rabbitmq-{{ env }}.learndaws.online
PAYMENT_HOST: payment-{{ env }}.learndaws.online
app_version: v3