RABBITMQ_PASSWORD: "{{ lookup('amazon.aws.aws_ssm', '/roboshop/dev/rabbitmq_password', region='us-east-1', decrypt=True) }}"
# "{{ (lookup('amazon.aws.aws_secret', 'roboshop/dev/rabbitmq_password', region='us-east-1') | from_json).RABBITMQ_PASSWORD }}"
